# Generated by Django 3.1.2 on 2020-12-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201226_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('EYE', 'EYE'), ('HEART', 'HEART'), ('GENERAL', 'GENERAL'), ('BRAIN', 'BRAIN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
