# Generated by Django 3.1.2 on 2020-12-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201226_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
