# Generated by Django 3.1.2 on 2020-12-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201227_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
