# Generated by Django 3.1.2 on 2020-12-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201227_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
