# Generated by Django 3.1.4 on 2020-12-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201227_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100, null=True)),
                ('salt_name', models.CharField(max_length=100, null=True)),
                ('dosageperday', models.IntegerField(null=True)),
                ('no_of_days', models.IntegerField(null=True)),
                ('appoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment')),
            ],
        ),
    ]
